
------ FUNCOES

---- CAPTURAR QUANTIDADE ESPECIFICA DE UMA STRING

-- SUBSTRING
SELECT LEFT(descricao, 4) FROM categorias -- CAPTURAS AS 4 PRIMEIRAS LETRAS
SELECT RIGHT(descricao, 4) FROM categorias -- CAPTURAS AS 4 ULTIMAS LETRAS
SELECT SUBSTRING(descricao, 2, 4) FROM categorias -- A PARTIR DO CARACTERE 2 CAPTURAS AS 4 PRIMEIRAS LETRAS

-- CONCAT
SELECT CONCAT('WAGNER ', 'LIMA ', 'ARAUJO') -- CONCATENAR STRING
SELECT CONCAT(descricao, ' TESTE') FROM categorias -- CONCATENAR STRING COM CAMPO EXISTENTE DA TABELA

-- ISNULL
SELECT ISNULL(NULL, 'SE FOR NULL RETORNA ESSE TEXTO')
SELECT ISNULL(descricao, 'SEM DESCRICAO') FROM categorias -- SE FOR NULL RETORNA O TEXTO 'SEM DESCRICAO'

-- COALESCE
--EX:
SELECT COALESCE (TEL1, TEL2, TEL3)  -- É PERMITIDO PASSAR UMA LISTA DE VARIAVEIS. E ESSA FUNCTION IRÁ RETORNAR O PRIMEIRO VALOR QUE ENCONTRAR E QUE NAO SEJA NULO.

-- IIF E LEN 

SELECT IIF(1 > 0, 'MAIOR QUE ZERO', 'MENOR QUE ZERO')
SELECT IIF(0 > 0, 'MAIOR QUE ZERO', 'MENOR QUE ZERO')
SELECT IIF(LEN(descricao) > 5, 'MAIOR QUE 5', 'MENOR QUE 5'), descricao FROM categorias -- VERIFICA SE O TAMANHO DA STRING É MAIOR QUE 5

-- GETDATE E CAST

SELECT GETDATE()
SELECT CAST(GETDATE() as DATE) -- CONVERTE SÓ P/ DATA