----- NOLOCK

SELECT * FROM categorias (NOLOCK) -- COM O NOLOCK VOCE CONSEGUE FAZER SELECT QUANDO UMA TRANSACAO ESTÁ ABERTA


---- TRANSACOES 
--BEGIN TRAN
--UPDATE categorias SET descricao = UPPER(descricao) WHERE id = 5

--COMMIT
--ROLLBACK
