----- CRIANDO SEQUENCE

CREATE SEQUENCE MinhaSequencia
AS INT -- INT: TIPO QUE A SEQUENCIA VAI RETORNAR
START WITH 6 -- IRÁ INICIALIZAR A PARTIR 6
INCREMENT BY 1 -- INCREMENTA DE 1 EM 1
MINVALUE 6 -- O VALOR MINIMO PARA INICIAR É 6
MAXVALUE 1000 -- O VALOR MAXIMO É 1000
NO CYCLE -- QUANDO ATINGIR O VALOR MAXIMO IRÁ RETORNAR UM EXCECAO


-- USAR A SEQUENCIA

SELECT NEXT VALUE FOR MinhaSequencia AS CONTADOR -- A CADA SELECT EXECUTADO INCREMENTA +1


--DICA:
-- UM EXEMPLO DE USAR SEQUENCIAS É CRIANDO UM CONTADOR PARA VERIFICAR QUANTOS ACESSOS SEU SITE OU APP TEVE


-- CRIANDO TABELA E UTILIZANDO A SEQUENCIA 'MinhaSequencia' NO INT

CREATE TABLE TabelaTesteParaSequencia
(
	ID INT DEFAULT NEXT VALUE FOR MinhaSequencia, -- UTILIZANDO A SEQUENCIA 'MinhaSequencia' NO INT
	DESCRICAO VARCHAR(100)
)

INSERT INTO TabelaTesteParaSequencia(DESCRICAO) VALUES('TESTE 02')

SELECT * FROM TabelaTesteParaSequencia